insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'HT000001','PITA DE AMARRE; MATERIAL ALGODÃ“N',12,118);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'PG000004','CAJA DE CARTON; ESPECIAL PARA ARCHIVO; DIFERENTE MEDIDA',4,86);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'PE000008','PAPEL BOND; TAMAÃ‘O CARTA; DE 75 GRAMOS; COLOR BLANCO; PRESENTACION PAQUETE DE 500 HOJAS',11,52);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'PE000009','PAPEL BOND; TAMAÃ‘O OFICIO; DE 75 GRAMOS; COLOR BLANCO; PRESENTACION PAQUETE DE 500 HOJAS',11,52);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'PE000010','PAPEL BOND; TAMAÃ‘O CARTA; DE 75 GRAMOS; COLOR VARIOS;  PRESENTACION PAQUETE DE 500 HOJAS',11,52);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'PG000019','SOBRE MANILA; TAMAÃ‘O CARTA; PRESENTACION PIEZA',4,109);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'PG000021','SOBRE MANILA; TAMAÃ‘O OFICIO; PRESENTACION PIEZA',4,109);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'PE000037','PAPEL; AUTOADHESIVO',9,71);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000002','ALMOHADILLA; PARA  PIZARRA  ACRILICA',4,834);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000006','BANDERITAS  ADHESIVAS; SEÃ‘ALADORES DE PAGINA; DE DIFERENTE MEDIDA; COLOR SURTIDO;  PRESENTACION POR JUEGO',14,839);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000012','BOLIGRAFO; DESECHABLE; MATERIAL BASE PLASTICO; TRAZO FINO; COLOR DE TINTA  AZUL',4,842);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000014','BOLIGRAFO; DESECHABLE; MATERIAL BASE PLASTICO; TRAZO FINO; COLOR DE TINTA ROJO',4,842);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000017','GOMA DE BORRAR; DIFERENTE CARACTERISTICA;  PRESENTACION POR PIEZA',4,843);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000024','CINTA ADHESIVA; ANCHO 18 MMS.; MATERIAL POLIPROPILENO; COLOR TRANSPARENTE',6,524);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000008','NOTA ADHESIVA; POST-IT REMOVIBLES; DIMENSION 76 X 76 MMS.; COLOR SURTIDO; PRESENTACION BLOCK X 100 HOJAS',10,841);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000029','CLIPS PARA PAPEL; NUMERO  33 MM.; MATERIAL  METAL;  PRESENTACION CAJA  X 100 UNIDADES',1,526);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000030','CLIPS PARA PAPEL; NUMERO  50 MM.; MATERIAL  METAL; PRESENTACION CAJA X 100 UNIDADES',1,526);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000025','CINTA MASKING; DE DIFERENTE MEDIDA; MATERIAL DE PAPEL; DE FACIL DESPRENDIMIENTO',6,847);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'ML000001','ALCOHOL; EN GEL; PRESENTACION FRASCO',3,849);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'ML000002','AMBIENTADOR; EN AEROSOL; DIFERENTE CARATERISTICA Y FRAGANCIA',3,849);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000043','ENGRAPADORA; TAMAÃ‘O MEDIANO; MATERIAL METALICO;  NÂº DE GRAPA 24/6 - 26/6',4,850);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000046','ESTILETE; TAMAÃ‘O GRANDE',4,851);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000051','FOLDER PLASTICO; TAMAÃ‘O OFICIO; COLORES VARIOS',4,855);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000068','GRAPA; NUMERO 24/6; MATERIAL COBRE;  PRESENTACION 1.000 X CAJA',1,537);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'ML000025','DETERGENTE GRANULADO;  PRESENTACION  BOLSA',17,849);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'ML000032','FRANELA PARA LIMPIEZA; PRESENTACION POR METRO',13,849);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000072','LAPIZ; COLOR NEGRO;  PRESENTACION POR PIEZA',4,860);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000074','LAPIZ; COLOR BICOLOR;  PRESENTACION POR PIEZA',4,860);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'ML000039','LAVANDINA; DESENGRASANTE; PRESENTACION POR LITRO',16,849);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'ML000033','GUANTES; MATERIAL LANA CON PALMA DE GOMA PARA LIMPIEZA; PRESENTACION PAR',4,849);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'ML000056','TRAPO PLOMO; PARA PISO',4,849);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000076','MARCADOR PARA PIZARRA ACRILICA; COLOR  SURTIDO',4,862);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000077','MARCADOR PERMANENTE; PUNTA GRUESA; COLORES  VARIOS',4,862);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000087','PEGAMENTO EN BARRA; ENVASE TUBO PLASTICO; CONTENIDO 21 GRS.',4,868);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000094','PORTA CLIPS MAGNETICO; MATERIAL ACRILICO; DIFERENTE CARACTERISTICA',4,871);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000075','MARCADOR PARA DISCO COMPACTO;  COLOR NEGRO',4,862);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'ML000046','PAPEL TOALLA; REUTILIZABLE; PRESENTACION POR ROLLO',6,849);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000111','REGLA  PLANA GRADUADA; MATERIAL PLASTICO; LONGITUD 30 CMS.',4,550);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000115','RESALTADOR DE TEXTO;  COLORES  VARIOS; PRESENTACION PIEZA',4,882);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000117','SACAGRAPA; MATERIAL CON AGARRADOR PLASTICO',4,551);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000137','TAJADOR ESCOLAR; PRESENTACION POR PIEZA',4,557);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000144','TAPA PLASTICA; TAMAÃ‘O OFICIO; COLORES  VARIOS',9,559);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000145','TIJERA PARA CORTAR PAPEL; MATERIAL ACERO BRUÃ‘IDO; MANGO PLASTICO; DIFERENTE MEDIDA  ',4,885);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000146','TINTA PARA SELLO AUTOMATICO; COLORES  VARIOS',3,560);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000138','TAMPO PARA SELLO; MATERIAL METALICO',4,558);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000129','SUJETA PAPEL BINDER; TAMAÃ‘O 19 MMS. (Â¾ PLG.); PRESENTACION CAJA DE 12 UNIDADES',1,883);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000134','TABLERO PARA NOTA; MATERIAL PLASTICO',4,555);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000193','TONER PARA IMPRESORA; MODELO HP COLOR LASERJET CP 3505, 3600, 3800; 501A; COLOR TINTA NEGRO; SERIE Q6470A',4,888);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000196','TONER PARA IMPRESORA; MODELO HP COLOR LASERJET 3600; 502A; COLOR TINTA YELLOW; SERIE Q6472A',4,888);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000236','TONER PARA IMPRESORA; MODELO HP LASERJET 1000, 1005, 1200, 1220, 3300, 3380; 15A; COLOR TINTA NEGRO; SERIE C7115A',4,888);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000240','TONER PARA IMPRESORA; MODELO HP LASERJET 1010, 1012, 1015, 1018, 1020, 1020 PLUS, 1022, 3015, 3020, 3030, 3050Z, 3052, 3055, M1005 MFP, M1319F MFP; COLOR TINTA NEGRO; SERIE Q2612A',4,888);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000252','TONER PARA IMPRESORA; MODELO HP LASERJET 4000, 4050; 27X; COLOR TINTA NEGRO; SERIE C4127X',4,888);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000235','TONER PARA IMPRESORA; MODELO HP LASER JET; 400-M401, 400-M425; COLOR TINTA NEGRA; SERIE CF280X',4,888);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000268','TONER PARA IMPRESORA; MODELO HP LASERJET II, IID â€“ III, IIID; COLOR TINTA NEGRA; SERIE 92295A',4,888);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000269','TONER PARA IMPRESORA; MODELO HP LASERJET M1212; COLOR TINTA NEGRO; SERIE CE285A',4,888);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000273','TONER PARA IMPRESORA; MODELO HP LASERJET P1005, P1006; 35A; COLOR TINTA NEGRO; SERIE CB435A',4,888);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000279','TONER PARA IMPRESORA; MODELO HP LASERJET P3015; 55X;  COLOR TINTA NEGRO; SERIE CE255X',4,888);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000284','TONER PARA IMPRESORA; MODELO HP LASERJET PRO P1566, P1606; COLOR TINTA NEGRO; SERIE CE278A',4,888);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000294','TONER PARA IMPRESORA; MODELO HP COLOR LASERJET 3600; 502A; COLOR TINTA MAGENTA; SERIE Q6473A',4,888);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000241','TONER PARA IMPRESORA; MODELO HP LASERJET 1100, 1100A 3200, 3200M; COLOR TINTA NEGRO; SERIE C4092A',4,888);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000275','TONER PARA IMPRESORA; MODELO HP LASERJET P2055; ALTA CAPACIDAD; 05X; COLOR TINTA NEGRO; SERIE CE505X',4,888);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'ME000004','ARRANCADOR PARA TUBO FLUORESCENTE; ESTANDAR; POTENCIA 40 WATS.; CORRIENTE 220/240 VOLTS.',4,567);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'ME000016','CABLE ELECTRICO; CORDON PARALELO BIPOLAR; NUMERO 18; PRESENTACION POR METRO',13,569);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'ME000008','INTERRUPTOR; MATERIAL PLASTICO; NUMERO DE TOMAS SIMPLE',4,606);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'ME000047','ENCHUFE; PLACA SIMPLE; MATERIAL PLASTICO',4,585);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'ME000037','CINTA AISLANTE',6,575);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'ME000078','SOQUET ELECTRICO; PARA COLGAR; DIFERENTE MATERIAL',4,615);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'ME000081','TERMICO; MATERIAL PLASTICO; CORRIENTE DIFERENTE AMPERIO; BIPOLAR; 220/240 V.',4,619);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'ME000038','CLAVIJA ; MATERIAL PVC.',4,576);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000327','PAPEL MULTICOLOR PARA CUBO; DIMENSION 9 X 9 CMS.; PRESENTACION 500 HOJAS',11,892);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'ME000069','REACTANCIA; POTENCIA 20 WATS.; VOLTAJE 220 V â€“ 50  Hz',4,609);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000334','CUADERNO CON ESPIRAL; TAMAÃ‘O NORMAL; TAPA CARTON; HOJA CUADRICULADADA; PRESENTACION 100 HOJAS',4,529);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000336','CUADERNO CON ESPIRAL; TAMAÃ‘O OFICIO; TAPA CARTON; HOJA CUADRICULADADA; PRESENTACION 100 HOJAS',4,529);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'ME000098','ZOCALO; PARA TUBO FLUORESCENTE; FIJO',4,628);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'ME000051',' FOCO HALOGENO ; DE DIFERENTE POTENCIA Y VOLTAJE',4,586);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000058','GRAPA; NUMERO 23/8; MATERIAL METALICO; PRESENTACION 1.000 X CAJA',1,537);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000383','TONER PARA FOTOCOPIADORA; MODELO SHARP SF-2020, 2116, 2118, 2120; COLOR TINTA NEGRO',4,895);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000132','SUJETA PAPEL BINDER; TAMAÃ‘O 41 MMS. (1 5/8 PLG.); PRESENTACION CAJA DE 12 UNIDADES',1,883);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000388','TINTA NEGRA EPSON; FX-2170/2180; LQ 2170/2080; SO15086',4,896);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000405','CINTA PARA IMPRESORA; EPSON FX 1170; CARRO LARGO',4,896);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000407','CINTA PARA IMPRESORA; EPSON LQ 1070; CARRO LARGO',4,896);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'AA000001','ALIMENTO PARA PERROS',17,910);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000003','ARANDELA  AUTOADHESIVA; MATERIAL PLASTICO; PRESENTACION POR BOLSA',17,835);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'PE000059','PAPEL BOND; TAMAÃ‘O CARTA; DE 75 GRAMOS; COLOR PERIODICO RECICLADO; PRESENTACION PAQUETE DE 500 HOJAS',11,52);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'PG000037','CARTULINA; LISA; COLOR VARIOS; TAMAÃ‘O CARTA; GRAMAJE 180 GRS.; PRESENTACION POR HOJA',9,90);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'PE000063','PAPEL CARBONICO PAR TRABAJOS EN MAQUINA DE ESCRIBIR',9,56);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000485','FOLDER; MATERIAL CARTULINA, TAMAÃ‘O OFICIO; COLOR AMARILLO',8,894);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'ML000094','JABON LIQUIDO PARA DISPENSADOR DE LAVAMANOS',4,849);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'ML000084','GUANTES PARA LIMPIEZA DE GOMA; COLOR NARANJA TALLA L',4,849);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000521','FOLDER MATERIAL CARTULINA TAMAÃ‘O CARTA COLOR AMARILLO',8,894);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000526','FOLIADORDE SEIS DIGITOS',4,534);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'ME000116','TUBO FLUORESCENTE POTENCIA 20 WATT  LONGITUD 60 CM',1,586);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'PE000069','ROLLO DE PAPEL PARA CALCULADORA',6,918);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'PE000070','BLOCK DE PAPEL BOND RAYADO TAMAÃ‘O CARTA',10,71);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000535','CINTA ROTULADORA DYMO',6,903);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000536','CINTA NEGRA PARA IMPRESORA EPSON LX300',4,896);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000537','CINTA PARA IMPRESORA EPSON EX 8/1000',4,896);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000538','CLIP METALICO DE 28 MM PEQUEÃ‘O',1,526);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000539','FASTENER METALICO DE 8 MM',4,854);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000541','TUBO DE MINA COLOR ROJO 0.5',23,887);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000542','TINTA PARA TAMPO AZUL',57,560);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000543','TINTA PARA TAMPO NEGRO',3,560);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000544','TINTA PARA TAMPO ROJO',3,560);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000545','TINTA PARA TAMPO VERDE',3,560);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000546','TONER PARA FOTOCOPIADORA TOSHIBA T-1350',4,895);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000547','TONER PARA FOTOCOPIADORA MITA DC-1460/1470',4,895);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000548','TONER PARA IMPRESORA EPSON EPL5900 NÂ°S500100',4,888);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000549','CARTRIDGE T-0180201 STYLUS',4,561);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000550','TINTA PARA RECARGA DE CARTRIDGE',3,561);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000551','CARTUCHO S O 20047 EPSON STYLUS 820',4,561);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000552','CARTRIDGE PARA IMPRESORA BCI-11 COLOR',4,561);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000553','CARTRIDGE PARA IMPRESORA BCI-10',4,561);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000554','TONER KONICA MINOLTA BIZHUB 4700P',4,888);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000559','TONER PARA IMPRESORA HP CF-226X',4,888);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000560','TONER PARA IMPRESORA HP LASER JET 87A',4,888);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'ME000191','PILA NORMAL MEDIANA DE 1,5V',4,604);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'PE000071','SOLICITUD DE FOTOCOPIAS INTERNAS',10,52);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'PQ000138','PINTURA SINTETICA MATE BLANCO 0.9 LITROS',4,212);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000562','TONER CARTRIDGE PARA FAX PANASONIC KX-FA83',4,561);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000563','TINTA PARA SELLO NUMERADOR COLOR ROJO DE 20CC',3,560);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'OR000107','PROCESADOR PENTIUM 1 VELOCIDAD 200 GHZ SOCKET 7 INTEL',4,723);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'ML000104','PAÃ‘UELO DESECHABLE DOBLE HOJA',1,462);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'CL000009','GAS NATURAL VEHICULAR - GNV',67,1003);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'ML000105','ALCOHOL EN GEL DE 900ML',4,941);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'ML000106','LAVANDINA DE 5 LITROS',24,849);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'ML000107','MEDICLEAN DESINFECTANTE EN PASTILLAS 100U',3,849);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'ML000108','DESINFECTANTE DE AMBIENTES EN AEROSOL ',4,849);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'PE000040','PAPEL BLANCO PARA PARA FAX 30M',6,69);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000363','BLOCK DE PAPEL ADHESIVO (POST-IT) 51 X 76 MM',10,841);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000415','TONER PARA FOTOCOPIADORA XEROX 5018/20',4,895);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000315','CARTRIDGE PARA IMPRESORA 51629A',4,561);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000204','TONER PARA IMPRESORA HP M203 CF230A',4,888);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'ME000171','TUBOS LED, 20W DE 1.2M ',8,586);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000565','CARTRIDGE TINTA NEGRA PARA IMPRESORA EPSON L3150; 544',4,561);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000566','CARTRIDGE TINTA CYAN PARA IMPRESORA EPSON L3150; 544',4,561);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000567','CARTRIDGE TINTA MAGENTA PARA IMPRESORA EPSON L3150; 544',4,561);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000568','CARTRIDGE TINTA YELLOW PARA IMPRESORA EPSON L3150; 544',4,561);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000573','CARTRIDGE TINTA NEGRO PARA IMPRESORA EPSON L355, L365; NÂ° 664',4,561);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000574','CARTRIDGE TINTA CYAN PARA IMPRESORA EPSON L355, L365; NÂ° 664',4,561);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000575','CARTRIDGE TINTA MAGENTA PARA IMPRESORA EPSON L355, L365; NÂ° 664',4,561);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000576','CARTRIDGE TINTA YELLOW PARA IMPRESORA EPSON L355, L365; NÂ° 664',4,561);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'PE000072','PAPEL BOND COLOR ROJO; TAMAÃ‘O CARTA; PAQUETE DE 500 HOJAS 75Gr',11,60);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'PG000044','ARCHIVADOR DE PALANCA PLASTIFICADO LOMO ANCHO; TAMAÃ‘O OFICIO',4,1050);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'PG000045','ARCHIVADOR DE PALANCA PLASTIFICADO MEDIO LOMO; TAMAÃ‘O OFICIO',4,1050);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'PG000046','ARCHIVADOR DE PALANCA PLASTIFICADO; ARCHIVADOR LETRA',4,1050);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000484','DISCO COMPACTO, CAPACIDAD 4.7 GIGABYTES, TIPO DVD  VIRGEN; SIN TAPA PLASTICA',8,848);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'ME000007','INTERRUPTOR; MATERIAL PLASTICO; NUMERO DE TOMAS DOBLE',4,606);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'CL000010','GASOLINA ESPECIAL ',16,150);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000382','TONER PARA FOTOCOPIADORA; MODELO CANON IR 1018/1019/1020/1021 IR 1022/1023/1024/1025; COLOR NEGRO; SERIE NPG-15',4,895);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'NM000119','PULVERIZADOR MANUAL; TIPO FUMIGADOR; MATERIAL PLÃSTICO; CAP. 2 L',4,1051);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'NM000121','LENTES DE PROTECCIÃ“N TRANSPARENTE; ANTIPARRA/ANTIEMPAÃ‘ANTE',4,1053);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'IM000056','BARBIJO KN-95; 5 CAPAS DE FILTRACIÃ“N; CON SUJETADOR DE OREJAS Y CLIP NASAL AJUSTABLE ',4,1048);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'IM000057','BARBIJO QUIRURGICO DE 3 CAPAS DE FILTRACIÃ“N; DESCARTABLE; PRESENTACIÃ“N CAJA DE 50 UNIDADES',1,1048);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'PQ000140','ALCOHOL DESINFECTANTE DE 70Â°; 2 LITROS',25,178);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'NM000122','PEDILUVIO MATERIAL PLÃSTICO',4,1047);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'NM000123','MASCARA DE PROTECCIÃ“N FACIAL TRANSPARENTE; ANTIEMPAÃ‘ANTE',4,1054);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000577','CLIP PARA PEPEL BINDER PRESENTACION CAJA DE 12 UNIDADES 51mm 2',1,883);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000578','TINTA PARA IMPRESORA EPSON L1800 673 YELLOW',4,899);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000579','TINTA PARA IMPRESORA EPSON L1800 673 NEGRO',4,899);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000580','TINTA PARA IMPRESORA EPSON L1800 673 MAGENTA',4,899);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000581','TINTA PARA IMPRESORA EPSON L1800 673 CYAN',4,899);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'ML000111','PAÃ‘UELO DESECHABLE TRIPLE HOJA',1,457);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'ML000112','FRANELA PARA LIMPIEZA, TAMAÃ‘O 50*50 cm',4,983);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000131','SUJETA PAPEL BINDER; TAMAÃ‘O 32 MMS. (1 Â¼ PLG.); PRESENTACION CAJA DE 12 UNIDADES',1,883);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'ME000109','PILA SECA; GRANDES D; 1.5 VOLTS',100,604);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'ME000193','ENCHUFE DE DOS TOMAS; MATERIAL PVC.',58,585);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'ME000194','FOCOS LED; AHORRADORES DE 9 WATS; COLOR BLANCO',4,586);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'PQ000057','SILICONA; SELLADOR TRANSPARENTE; PRESENTACION TUBO; CONTENDO 280 ML.',4,222);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'ME000043','CORTAPICO; 6 SALIDAS; VOLTAJE 110/220',4,579);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'ME000195','PILAS ALCALINAS AAA DE 1,5 VOLTIOS, PAQUETE DE SEIS UNIDADES',11,604);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'ML000110','GUANTE  DE LATEX; PRESENTACIÃ“N CAJA DE 50 PARES, NO QUIRURGICOS; COLOR BLANCO',1,849);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000026','CINTA DE EMBALAJE; ANCHO  48  MMS.; MATERIAL POLIPROPILENO: COLOR  TRANSPARENTE, 200 YARDAS ',6,846);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000091','PERFORADORA  METALICA; DE 2 PERFORACIONES; PARA 40 HOJAS, BANDEJA PLASTICA DE DESECHOS',4,869);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000037','DISCO COMPACTO CD, CAPACIDAD 700 MB.',4,848);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000034','CORRECTOR EN CINTA; COLOR BLANCO',4,528);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000079','MICROPUNTA; COLOR TINTA AZUL; ENVASE PLASTICO; PUNTA 0.7',4,863);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'ML000113','DETERGENTE LIQUIDO LAVA VAJILLA PRESENTACION FRASCO 1050 ML',3,459);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'ML000114','AMBIENTADOR PARA AUTO, TIPO ARBOLITO',4,457);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000583','TAMBOR DE TRASFERENCIA DE IMAGENES  LASERJETHP CF232A (32A)',4,1045);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'PG000048','CUADERNO CON ESPIRAL, TAMAÃ‘O OFICIO, HOJA CUADRICULADA',4,103);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'PG000049','CUADERNO ESPIRAL TAMAÃ‘O MEDIO OFICIO, HOJA CUADRICULADA',4,103);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'PG000050','PAPEL CUBO 9*9 CM; MULTICOLOR PAQUETE DE 500 HOJAS',4,103);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000584','ORGANIZADOR DE ESCRITORIO METALICO TIPO RED, TRES DIVISIONES',4,864);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000585','CINTA ADHESIVA TRANSPARENTE DE 2 CM ANCHO',4,524);
insert into material.materiales(id_entidad,codigo,descripcion,id_unidad,id_categoria)values(1,'UE000586','BANDEJA DESLIZABLE COLOR NEGRO DE 3 PISOS',4,864);
